### ISSUE TITLE
Help on runnign the code

### ISSUE THREAD

**Issue by tcapelle** [ika-rwth-aachen/PCLSegmentation#7]
Hey, thanks for putting this out.
I am trying to run the code without success. I am using the docker image and using the train script.
I jumped inside the continer an trying to run this command manually without sucess:
```bash
python pcl_segmentation/train.py --data_path /src/dataset_samples/semantic_kitti/ \
 --train_dir /src/output --config squeezesegv2kitti --model squeezesegv2 --epochs 1
```
 but I get a non compile error from Keras:
```python
Traceback (most recent call last):
  File "pcl_segmentation/train.py", line 82, in <module>
    train(args)
  File "pcl_segmentation/train.py", line 54, in train
    model.fit(train,
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1420, in fit
    raise ValueError('Unexpected result of `train_function` '
ValueError: Unexpected result of `train_function` (Empty logs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.
```
Have you seen this before? Have any ideas on how to fix it?
Sincerely,
Thomas

> I am able to run the sample_dataset without issues, but would really like to be able to run kitti. Also, are there pretrained models available?

**Comment by TillBeemelmanns** [comment]
Hi @tcapelle,

thanks for posting this issue. Note that the default `batch size` in [SqueezeSegV2Kitti.py]( https://github.com/ika-rwth-aachen/PCLSegmentation/blob/main/pcl_segmentation/configs/SqueezeSegV2Kitti.py) is `64`. 

However, the dataset samples for semantic Kitti consists of 20 samples. So this is the reason why this does not work out of the box. The dataset samples are just for demonstration. You should download the whole semantic Kitti dataset, convert and use it for training. 

Currently I do not have any pretrained models. But I want to make them available soon, when I have capacity to do it. 

Best regards,

Till

**Comment by TillBeemelmanns** [comment]
I also updated the samples in `semantic_kitti`. Some of them were generated with a wrong configuration. I tested the code now. It seems to work now again. Let me know if you run into other issues.
